version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - 3001
    env_file:
      - .env
    networks:
      - dokploy-network
    depends_on:
      food-price-postgres:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.food-price-app.rule=Host(`food-price-inflation.soulfun.site`)
      - traefik.http.routers.food-price-app.entrypoints=websecure
      - traefik.http.routers.food-price-app.tls.certresolver=letsencrypt
      - traefik.http.services.food-price-app.loadbalancer.server.port=3001

  food-price-postgres:
    image: postgres:16
    container_name: food-price-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_food_price_inflation
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network

volumes:
  db_data:

networks:
  dokploy-network:
    external: true
