version: "3.8"

services:
  nextjs-app:
    container_name: nextjs-app
    build: .
    ports:
      - 3001
    env_file:
      - .env
    networks:
      - dokploy-network
#   db:
#     container_name: postgres
#     image: postgres:16
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: db_food_price_inflation
#     ports:
#       - "5434:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# volumes:
#   db_data:

networks:
  dokploy-network:
    external: true
