version: "3.8"

services:
  food-price-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001
    env_file:
      - .env
    networks:
      - dokploy-network
  food-price-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_food_price_inflation
    # ports:
    #   - 5435
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network

volumes:
  db_data:

networks:
  dokploy-network:
    external: true
